# ------------------------------------------------------------------------------------------
# Controle de funcoes do painel de usuario
# ------------------------------------------------------------------------------------------
# Ativar o painel de usuario
EnableUserPanel = False

# Ativa o comando .epic
# Mostra se algum GrandBoss esta vivo ou morto
EpicCommand = True

# Ativar o comando .combinetalismans
# Comando combina talismans do mesmo tipo em apenas 1 com o tempo de todos somados
CombineTalismansCommand = True

# Ativar o sistema DressMeSystem
# Os Sets, armaduras e outros sao configurados em "...game\data\dressme"
DressMeSystem = False

# Enables .changepassword voiced command which allows the players to change their account's password ingame.
# Default: False
AllowChangePassword = True


# ---------------------------------------------------------------------------
# Multilingual support
# ---------------------------------------------------------------------------
# Enable or disable multilingual support.
# Default: False
MultiLangEnable = True

# Default language, if not defined.
# Default: en
MultiLangDefault = en

# List of allowed languages, semicolon separated.
# Default: en;el
MultiLangAllowed = en;br

# If a localized HTML file is not found (e.g., in data/lang/...),
# the server will attempt to load the default language version (e.g., from data/lang/en).
# Default: True
RestoreHtmlByDefault = True

# Enable or disable voice command .lang for changing languages on the fly.
# Default: True
MultiLangVoiceCommand = True


# ---------------------------------------------------------------------------
# Auto Play Settings
# ---------------------------------------------------------------------------
# Enable player .play voiced command.
# Default: False
EnableAutoPlay = True

# Default: True
EnableAutoPotion = True

# Default: True
EnableAutoSkill = True

# Default: True
EnableAutoItem = True

# Resume auto play upon enter game.
# Retail: False
ResumeAutoPlay = False

# Assist party leader.
# When in party, target what the leader is targeting.
# Retail: False
AssistLeader = False

# Range Targeting.
# Default: ShortRange 500
# Default: LongRange 1000
ShortRange = 500
LongRange = 2000

# Enable .play command only for premium players.
# Premium System must be enabled.
# Default: False
AutoPlayPremium = False

# List of skills that cannot be added to auto play selection menu, separated by commas.
DisabledSkillIds = 42

# List of items that cannot be added to auto play selection menu, separated by commas.
DisabledItemIds =

# Message send to players on login.
# Leave empty to disable.
# Example: You can use .play to automate farming.
AutoPlayLoginMessage =


# ---------------------------------------------------------------------------
# Server Statistics
# ---------------------------------------------------------------------------
# Mostra a quantidade de players online em cada categoria disponivel seguindo a lista abaixo
# Players online
# Active Players
# Offline Shop
ServerStatistics = False
